### ISSUE TITLE
The name `JULES.jl` may be too generic

### ISSUE THREAD

**Issue by glwagner** [ali-ramadhan/Atmosfoolery.jl#68]
Just a note --- this repository is difficult to find with a google search. It might be a good idea to find a more specific and informative name.

**Comment by ali-ramadhan** [comment]
Never tried Googling but I can imagine.

Closely related to #30

**Comment by ali-ramadhan** [comment]
Lol apparently JULES is also a land-surface model: https://en.wikipedia.org/wiki/JULES

**Comment by glwagner** [comment]
How about `Atmosfoolery.jl`?

**Comment by ali-ramadhan** [comment]
I like it!

**Comment by ali-ramadhan** [comment]
Ah @thabbott might have to change the repo name.

**Comment by thabbott** [comment]
I like it too! And yeah I probably do have to be the one to change the
name---but I also feel like I should give ownership of the repo to Ali,
since he's done a lot more work on it than I have.

My wifi decided to give me a day off today, but I'll change the name and
transfer ownership once it's back up.

**Comment by ali-ramadhan** [comment]
Happy to hold onto the repo until we find a place for it!

@natgeo-wong expressed some interest in continuing development so maybe we end up transferring it to him some time in the future.

**Comment by glwagner** [comment]
Might be good to do this before we announce Oceananigans.jl on julia discourse, since we can mention this package as well and the fact that we're looking for contributors.
